M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-21T18:31:10+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-21T18:31:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X132.79Y-96.155
X140.99Y-96.155
M30
