M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu24.04.1} date 2025-09-14T23:51:24+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-14T23:51:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
%
G90
G05
T1
X5.228Y-3.7856
X5.5508Y-3.7856
M30
